### ISSUE TITLE
Start at zero position

### ISSUE THREAD

**Issue by wmandrews** [newsdev/ap-deja-vu#1]
Right now, elex-loader's `update.sh` script will always push deja-vu beyond position: 0, so it's not actually possible to queue up the position: 0 results.

Sets to zero:
http://campfin.newsdev.net/ap-deja-vu/2016-03-01?position=0&playback=1

Run `./update.sh`:
Pushes to position: 1.

**Comment by jeremyjbowers** [comment]
Fixed this with the new admin interface in sha 5f06f0ee6423cc2f4ddf9963cfc32ca601cf3eeb.
