### ISSUE TITLE
Filter initialization data

### ISSUE THREAD

**Issue by wmandrews** [newsdev/ap-deja-vu#4]
It would be nice to avoid keeping initialization data in the deja vu cycle, and instead just add a button to test what happens with initialization data like we do with error codes. It's difficult to know when and were the init data exists in a deja vu collection.

**Comment by jeremyjbowers** [comment]
We should handle this in the recording; the first file should be init data an dthen other files can be zeroed results.

**Comment by jeremyjbowers** [comment]
I am going to close this ticket but I will have to handle this manually -- there's not a good way to do this automagically just now.
